### ISSUE TITLE
metabat2 minimum contig size constraint

### ISSUE THREAD

**Issue by tommyfuu** [Meta-CAMP/camp_binning#1]
hi! there was one thing that was not exactly a bug with the binning pipeline but the pipeline should probably set up a warning for (my version of the pipeline is no longer up-tp-date with the repo so it's a bit hard for me to add the feature and test). When one wants to run metabat, they can set the `min_metabat_len` to whatever they feel like. It is important to note that metabat2 has the constraint that this value has to be >= 1500. If one sets this value to be, say, 1000, metabat2 will generate the following error:

```[Error!] Contig length < 1500 is not allowed to be used for binning.```

However, in my case, if i set `min_metabat_len = 1000`, the metabat2 in the pipeline fails silently without this error showing up or any warning. I initially thought that was because metabat2 did not generate any bins until i ran metabat2 by itself without the camp wrapper, after which it successfully generated bins. I think adding this as a user warning/error might be a good feature.

**Comment by lauren-mak** [comment]
Will be addressed in the next update. Thanks!
